server.port=${SERVER_PORT:8080}

# Base de datos - AWS RDS PostgreSQL
spring.datasource.url=jdbc:postgresql://fertilar.csf0sq6ogxjk.us-east-1.rds.amazonaws.com:5432/fertilar
spring.datasource.username=siga
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

# AWS Cognito
aws.cognito.region=${AWS_COGNITO_REGION}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}

# AWS S3
aws.s3.region=${AWS_S3_REGION:us-east-1}
aws.s3.certificados-bucket=${AWS_S3_CERTIFICADOS_BUCKET:fertilar-certificados}

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
spring.jackson.time-zone=America/Argentina/Buenos_Aires

# Logs
logging.level.org.springframework=INFO
logging.level.com.fertilar=DEBUG
