
server.port=${SERVER_PORT:8080}


spring.datasource.url=jdbc:postgresql://fertilar.csf0sq6ogxjk.us-east-1.rds.amazonaws.com:5432/fertilar
spring.datasource.username=siga
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Permite arrancar aunque la DB no esté disponible al inicio
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.maximum-pool-size=5

# AWS Cognito
aws.cognito.region=${AWS_COGNITO_REGION}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}

logging.level.org.springframework=INFO
logging.level.com.fertilar=DEBUG
